---

- assert:
    that:
      - 'haproxy_project_name != ""'
  tags:
    - all


- assert:
    that:
      - 'haproxy_prefix    != ""'
      - 'haproxy_container != ""'
  tags:
    - haproxy_configure


################################################################################
########## HAPROXY
################################################################################
- name: copy haproxy file (conf)
  template:
    src: "../templates/{{ item.src }}"
    dest: "/tmp/{{ item.dest }}"
  with_items: "{{ haproxy_conf_files }}"
  tags:
    - haproxy_configure


- name: configure haproxy (conf)
  command: "docker cp /tmp/{{ item.dest }} {{ haproxy_container }}:{{ haproxy_prefix }}/"
  with_items:
    - "{{ haproxy_conf_files }}"
  tags:
    - haproxy_configure


- name: remove haproxy files (conf)
  file:
    path: "/tmp/{{ item.dest }}"
    state: absent
  with_items:
    - "{{ haproxy_conf_files }}"
  tags:
    - haproxy_configure


- name: restart haproxy service
  service:
    name: "{{ haproxy_project_name }}"
    state: restarted
  tags:
    - haproxy_configure
